name: Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '8'
      - uses: joutvhu/write-file@v1
        with:
          path: src/main/resources/application.properties
          contents: ${{ secrets.APPLICATION_PROPERTIES }}
          write_mode: overwrite  
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: target/wordsaway-servlet-1.0-SNAPSHOT.jar  
        
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download JAR
        uses: actions/download-artifact@v2
        with:
          name: artifact
      #Deploy the artifact (JAR) into AWS Beanstalk
      - name: Deploy to EB
        uses: wsmith324/beanstalk-deploy@v2
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          use_existing_version_if_available: false
          application_name: BackendCICD
          environment_name: Backendcicd-env
          version_label: ${{github.SHA}}
          region: us-east-1
          deployment_package: wordsaway-servlet-1.0-SNAPSHOT.jar   
